### ISSUE TITLE
Request to change Primo sandbox banner

### ISSUE THREAD

**Issue by raybrarian** [uoregon-libraries/uolib-primo-nui#27]
After the sync of production Primo settings to the sandbox, it's difficult to tell at a glance which environment you are in. I know the prompt to login banner is on prod and not sandbox, but it would be great to have an additional cue.

Is it possible to change "LibrarySearch" to "LibrarySearch - Sandbox"?

**Comment by jechols** [comment]
Given the pending migration to VE where we won't have a sandbox I suspect this is a moot point. Feel free to reopen if I'm incorrect.
