### ISSUE TITLE
Revert OTB changes to facet look and feel

### ISSUE THREAD

**Issue by raybrarian** [uoregon-libraries/uolib-primo-nui#29]
Line height and font size of facets (shown on the left once search results are returned) are both significantly different from the current release, cutting off dropdown indicators. If possible to retain existing font size and line height while improving accessibility, that's preferred.

November release version: 
![facets](https://user-images.githubusercontent.com/4460510/102536993-3a5a4f80-405f-11eb-890a-0ad021900727.png)

**Comment by jechols** [comment]
This looks the same to me - I think perhaps @MargaretA-UO already fixed it via configs or something?

Current:

![image](https://user-images.githubusercontent.com/2157974/102828971-dc00da00-439a-11eb-9dfd-9cd2a8e252fe.png)

Sandbox:

![image](https://user-images.githubusercontent.com/2157974/102828988-e622d880-439a-11eb-8e13-d76d2d3b5dd0.png)

**Comment by MargaretA-UO** [comment]
I did. :-)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MargaretA-UO** [comment]
Verified.
