### ISSUE TITLE
Fix citation style highlight

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/uolib-primo-nui#30]
From document: "In link to this under Send To, the chosen Citation Style highlight is black, and the mouseover is grey. Make hover state Green on White. and current/selected state white text on black box."

FYI here are Reference images that were attached to the document

Nov release:
![image](https://user-images.githubusercontent.com/2157974/102674204-0740ba80-414a-11eb-9599-1865df65bb8c.png)

Current:
![image](https://user-images.githubusercontent.com/2157974/102674211-11fb4f80-414a-11eb-951f-df1dcc320168.png)

**Comment by jechols** [comment]
I need a link that demonstrates this.  I'm not seeing anything like this on an item that I search for (e.g., https://alliance-primo-sb.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=CP71113996260001451&context=L&vid=UO&lang=en_US&search_scope=everything&adaptor=Local%20Search%20Engine&tab=default_tab&query=any,contains,cat&offset=0)

**Comment by jechols** [comment]
@MargaretA-UO  / @ppatter2  - can one of you give me a link that demonstrates this issue?  Not sure which of you is best to pester about this stuff.

**Comment by MargaretA-UO** [comment]
I'm seeing this in the citation you provided, actually.

**Comment by MargaretA-UO** [comment]
Go to the full display of the record, click on Cite This Item in the Send it frame.

**Comment by ppatter2** [comment]
> I need a link that demonstrates this. I'm not seeing anything like this on an item that I search for (e.g., https://alliance-primo-sb.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=CP71113996260001451&context=L&vid=UO&lang=en_US&search_scope=everything&adaptor=Local%20Search%20Engine&tab=default_tab&query=any,contains,cat&offset=0)

When you get to this link you will want to scroll down the page and look for CITE THIS ITEM in the Send to section.  When you select this link than you will be able to see the navigation on the left for MLA, APA etc. Please let me know if you need more information.  
![Screen Shot 2020-12-18 at 4 30 23 PM](https://user-images.githubusercontent.com/74323806/102675640-08c0b180-414f-11eb-8748-b383085e2cfe.png)

**Comment by jechols** [comment]
Thanks! After looking at that, it turns out a different fix also fixed this issue.  Closing.

**Comment by MargaretA-UO** [comment]
Verified.
