### ISSUE TITLE
"My List" contrast

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/uolib-primo-nui#31]
In My List area, Saved searches, contrast for links in current release is significantly better than in new release, although the Saved Search underline is still a weird blue.  Contrast is an issue.

November release:
![image](https://user-images.githubusercontent.com/2157974/102674621-79fe6580-414b-11eb-8252-14f4658dd4ac.png)

Current:
![image](https://user-images.githubusercontent.com/2157974/102674628-7d91ec80-414b-11eb-9737-b0b33a54e710.png)

**Comment by jechols** [comment]
This may be extremely difficult to tackle.  I have no idea why the search results themselves have reverted to that contrast-failing blue.  It may take a very targeted CSS hack to fix this, which is always a good time.

**Comment by MargaretA-UO** [comment]
Verified.
