### ISSUE TITLE
Drop down arrows next to facets are the wrong color

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/uolib-primo-nui#32]
Arrows next to facets are blue, not green:

Sandbox:

![image](https://user-images.githubusercontent.com/2157974/102832257-b7106500-43a2-11eb-9a02-9bc7a956070d.png)

Prod looks like this:

![image](https://user-images.githubusercontent.com/2157974/102832288-cd1e2580-43a2-11eb-84f8-55a1fe224770.png)

**Comment by jechols** [comment]
Fixed (using UO Legacy Green)

**Comment by MargaretA-UO** [comment]
Looks so much better.  Verified.
