### ISSUE TITLE
Facet categories' hover/focus styling is inaccessible

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/uolib-primo-nui#33]
Used to have a dark background on hover/focus, but now the link just changes slightly.

Sandbox: 

![image](https://user-images.githubusercontent.com/2157974/102832678-effd0980-43a3-11eb-87b0-6e8903ccdb28.png)

Prod:

![image](https://user-images.githubusercontent.com/2157974/102832693-fa1f0800-43a3-11eb-895a-88c00e1e47e9.png)

**Comment by jechols** [comment]
Fixed to be more consistent with other links/buttons on hover/focus

**Comment by MargaretA-UO** [comment]
Verified it looks like what you said.

**Comment by MargaretA-UO** [comment]
Looks great.  Verified!
