### ISSUE TITLE
"Back to results list" link contrast fails

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/uolib-primo-nui#36]
![image](https://user-images.githubusercontent.com/2157974/102833030-d4dec980-43a4-11eb-9449-ef1cba3286bb.png)

**Comment by jechols** [comment]
I don't know if it changed (possibly due to other changes that bled into this area), but this seems to pass my Accessibility Insights checks as well as webaim's WAVE toolbar.  Closing.

**Comment by MargaretA-UO** [comment]
Verified.  That's fine.
