### ISSUE TITLE
Sidebar in full record display is wrong color

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/uolib-primo-nui#37]
In full display for a record, sidebar is a more opaque shade, and blue, instead of green.  Contrast is better, in fact, but wrong color.

Sandbox:

![image](https://user-images.githubusercontent.com/2157974/102833239-62bab480-43a5-11eb-9f45-9f52a5018d40.png)

Prod:

![image](https://user-images.githubusercontent.com/2157974/102833248-664e3b80-43a5-11eb-90b3-4e7ef807b434.png)

**Comment by jechols** [comment]
Fixed this, but contrast was a mess.  Used a much more opaque green, which required some changes to the way the buttons were being displayed on hover/focus.

It looks like this now:

![image](https://user-images.githubusercontent.com/2157974/102941667-24d29480-4468-11eb-827a-b928e66f076c.png)

(The white border is the really big change)

**Comment by MargaretA-UO** [comment]
Ha.  Looks good.  Verified.
