### ISSUE TITLE
Login background color changed to black

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/uolib-primo-nui#38]
Login screen in Nov Release is black with blue text.  Should be made to look like current, but with UO green links.

Sandbox:

![image](https://user-images.githubusercontent.com/2157974/102833332-aca39a80-43a5-11eb-8081-bfa0931dd71e.png)

Prod:

![image](https://user-images.githubusercontent.com/2157974/102833345-b0cfb800-43a5-11eb-8326-5e449f5d1151.png)

**Comment by jechols** [comment]
Given the contrast improvements in the current version and the timeline, this is low priority

**Comment by jechols** [comment]
Kept the black background (the contrast is way better), but changed the "links" (buttons?) so they were closer to our branding colors

**Comment by MargaretA-UO** [comment]
Ha!  That surprised me.  It's a vivid green on the black.  Better than it had been previously, I think.  Let's do it.  Verified.
