### ISSUE TITLE
QR code disappears into the header bar in production after release

### ISSUE THREAD

**Issue by MargaretA-UO** [uoregon-libraries/uolib-primo-nui#40]
In SB looks like this:
![image](https://user-images.githubusercontent.com/76136640/103486332-f6cb4980-4db1-11eb-8971-fa9198833ce1.png)
and hover like this:
![image](https://user-images.githubusercontent.com/76136640/103486389-5b86a400-4db2-11eb-8915-62434fd4959e.png)

In Prod looks like this:
![image](https://user-images.githubusercontent.com/76136640/103486352-12ceeb00-4db2-11eb-81c2-bd2a0969a9ed.png)
and hover like this:
![image](https://user-images.githubusercontent.com/76136640/103486320-e6b36a00-4db1-11eb-9b86-dbd2295831cc.png)

**Comment by jechols** [comment]
I cannot replicate this in Chrome, Edge, or Firefox.  @raybrarian "fixed" the issue by clearing cookies, so I'm not sure what the problem could be.  None of our customizations use cookies in any way, so this is something on the ExL side.

**Comment by MargaretA-UO** [comment]
I guess I should have tried that.  It now works for me, as well.
Thanks!

**Comment by jechols** [comment]
No worries, I have no idea how/why this could even happen.  Very weird.
