### ISSUE TITLE
Primo VE dev tools

### ISSUE THREAD

**Issue by MargaretA-UO** [uoregon-libraries/uolib-primo-nui#41]
Into to VE DevEnv, fwiw  [Using the Development Environment for Primo VE (5:27](https://urldefense.com/v3/__https://drive.google.com/file/d/1bf0ZarCOVN2g8kAeEpO8-ooOMKPw-nll/view?usp=sharing__;!!C5qS4YX3!VZHxEreqApesh3b0fqIdFi7NmFHhuuAtcHyBi_WDbkrovIPjlzigizYB4FDAVn-8SMQ$)) 
Alliance customizations in a new [Primo VE Toolkit ](https://urldefense.com/v3/__https://www.orbiscascade.org/programs/systems/pcsg/primo-ve-toolkit/__;!!C5qS4YX3!VZHxEreqApesh3b0fqIdFi7NmFHhuuAtcHyBi_WDbkrovIPjlzigizYB4FDAPm3LLf4$)

**Comment by jechols** [comment]
I've put this info in our ADI onedrive: General\Primo VE\development-implementation
