### ISSUE TITLE
VE - Show/Hide Summit Libraries

### ISSUE THREAD

**Issue by MargaretA-UO** [uoregon-libraries/uolib-primo-nui#46]
Working in Primo, not in VE.  See Alliance customization: https://www.orbiscascade.org/programs/systems/pcsg/primo-ve-toolkit/collapse-other-institutions/ 

Implementation
In your custom.js, you should have the following line to define the app variable. There may be other modules listed in the brackets.

var app = angular.module('viewCustom', ['angularLoad']);

Paste in the following code:

app.component("prmAlmaOtherMembersAfter", {
  bindings: {
    parentCtrl: "<",
  },
  controller: [
    function () {
      var ctrl = this;
      ctrl.parentCtrl.isCollapsed = true;
    },
  ],
});

**Comment by jechols** [comment]
Can you let me know how to see this on the current site so I know what's missing? I'm seeing this on VE, so I'm not sure what precisely needs to be there instead:

![image](https://user-images.githubusercontent.com/2157974/153273916-42afe6e1-3361-453e-81f2-0b8045b4d63c.png)

**Comment by MargaretA-UO** [comment]
We would like the list of Summit Libraries to be collapsed by default.  Here it is in Primo: 
![image](https://user-images.githubusercontent.com/76136640/153286136-d5e45427-b709-4e7f-8a68-3e6a57a93830.png)

**Comment by jechols** [comment]
Fixed this - will deploy later for QA

**Comment by MargaretA-UO** [comment]
Confirmed working.
