### ISSUE TITLE
VE - Custom images not loading

### ISSUE THREAD

**Issue by MargaretA-UO** [uoregon-libraries/uolib-primo-nui#47]
Noticed so far:
WorldCat logo (do a nonsense search "adsklfjldgkaj" and get no results message, logo should appear at bottom of message)
Peer Reviewed icon should be green people, is instead a purple icon: example https://alliance-uoregon.primo.exlibrisgroup.com/permalink/01ALLIANCE_UO/1m41ln5/cdi_crossref_primary_10_1080_1362704X_2019_1627758

**Comment by jechols** [comment]
WorldCat is fixed. Not sure why the "peer review" override is busted. Still looking into that one.

**Comment by jechols** [comment]
Peer review icon fixed thanks to @MargaretA-UO (and her contacts who know angular way better than I ever will)
