### ISSUE TITLE
VE: Fix "report a problem" generated link

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/uolib-primo-nui#48]
This piece seems to work (I think?) but it's sending the wrong URL for VE. That needs to be changed to the VE URL.

e.g., if you visit https://alliance-uoregon.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma99122099390001451&context=L&vid=01ALLIANCE_UO:UO and activate "Report a Problem", you get sent to the "problem" page, but the URL there is reported as http://alliance-primo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?vid=01ALLIANCE_UO:UO&docid=alma99122099390001451&context=L - this is obviously incorrect.

**Comment by jechols** [comment]
This is as fixed on the primo side as it can be. When we launch, we have to change how the library handles problem links, because the library code fills in the server (e.g., "https://alliance-uoregon.primo.exlibrisgroup.com"). So while the path is now fixed, the library site still have the old server info, and we can't safely change that until launch.

**Comment by MargaretA-UO** [comment]
And that’s something you will need to do, is that correct?  I’ll add it to my go-live list.

**Comment by jechols** [comment]
Yup, it's something I'll have to fix on the UO library site, which can't be set up prior to VE being ready (otherwise "problem" URLs will be wrong), *and* we can't even test the thing until after that fix happens, which means we can't test until after VE is live. Not ideal, but this isn't something we can avoid.
