### ISSUE TITLE
Primo VE live date Banner needed on Primo, and remove login links

### ISSUE THREAD

**Issue by MargaretA-UO** [uoregon-libraries/uolib-primo-nui#51]
On the morning we go live on Primo VE, we'll need to remove the login links on the old Primo.

Here's a snippet of code that Bill Kelm @ Willamette shared to remove login links:
Snippet to hide login in Primo:
(Bill - Willamette)/* Hide Sign in Link */ .alert-bar {     display:none;     } .user-menu-button, .view-switcher {     display:none; } /* Hide the sign in link */  .alert-bar {     display:none; }  /* Hide Guest */  prm-user-area .user-menu-button .user-name {     display: none; }  /* Hide My Library Card */  prm-library-card-menu {     display: none;  }

**Comment by MargaretA-UO** [comment]
Ex Libris' document on removing login links: https://knowledge.exlibrisgroup.com/Primo/Knowledge_Articles/Hide_references_to_sign_in_and_authentication_in_Primo_Front_End

**Comment by jechols** [comment]
@MargaretA-UO How long after go-live do we expect to need the legacy site to have our code? (I'll have to maintain a "legacy" branch of the VE code)

**Comment by MargaretA-UO** [comment]
I'm not sure what you mean?  The old Primo site will stay accessible for the month of July, but not publicly linked (at least intentionally)

**Comment by jechols** [comment]
I apologize: my above comment was a mistake. I was trying to type mid-meeting. I *meant* to say I'll have to maintain a legacy branch of the **Primo NUI** code, not a legacy branch of the VE code.

Basically I want to know how long I should hold onto the legacy Primo code. Say we have a need to put a new message in its banner or something. Anyway I think you answered that question: it sounds like after July I can get rid of it.

**Comment by MargaretA-UO** [comment]
No worries.  I'd say plan for a week or so into August, just in case.

**Comment by MargaretA-UO** [comment]
Another solution to hiding login links from Blake: 

/*Hide Ellipsis Page (aka Show More) Sign In*/
prm-main-menu div.settings-container.align-self-stretch.layout-gt-xs-row.layout-align-center-start {
display: none;
}
/*Hide QR Code and My Favorites Shortcut*/
div:nth-child(1) prm-search-bookmark-filter {
display: none;
}
div:nth-child(2) prm-search-bookmark-filter {
display: none;
}
/*Hide User Menu Sign In*/
prm-user-area-expandable {
display: none;
}
/*Hide Alert Bar Sign In*/
.alert-bar {
display:none;
}
/*Hide Login Card Sign In*/
prm-stand-alone-login md-card {
display: none;
}
