### ISSUE TITLE
VE: Frame for "Send to" incomplete

### ISSUE THREAD

**Issue by MargaretA-UO** [uoregon-libraries/uolib-primo-nui#53]
The upper left bracket graphic is missing in the Send To section in VE:
![image](https://user-images.githubusercontent.com/76136640/161440864-81876a41-1da2-4413-90ee-47b082c30a9d.png)

**Comment by MargaretA-UO** [comment]
Checking Primo classic, it's also missing there.  
It just looks sloppy.  Not huge priority, of course.

**Comment by jechols** [comment]
If you don't mind dropping that shadow entirely, I think that's actually the best option. Some of the other customizations in the same CSS appear to break accessibility in odd little ways, and the rules aren't very well explained. I suspect these are rules somebody created to fix a problem that's either no longer present, or which wasn't able to be fully fixed anyway.

Here's what it looks like without the shadow:

![image](https://user-images.githubusercontent.com/2157974/176518281-46c74709-e9ce-4061-ab32-e379c676efb1.png)

As an added bonus, dropping these CSS rules fixes the "Related Items" box to have next and previous buttons:

Old:

![image](https://user-images.githubusercontent.com/2157974/176518464-140fc134-af50-483c-8822-3cfdbda7a44a.png)

New:

![image](https://user-images.githubusercontent.com/2157974/176518491-1661fa4d-7eed-4782-8421-ccfa411083b9.png)

**Comment by MargaretA-UO** [comment]
Looks good.
