### ISSUE TITLE
Angular version changing Nov 2022

### ISSUE THREAD

**Issue by MargaretA-UO** [uoregon-libraries/uolib-primo-nui#54]
From Ex Libris documentation:
Upgrade to Angular 1.8 in Primo/Primo VE – We plan to upgrade from Angular 1.6.10 to Angular 1.8 in the Primo/Primo VE November 2022 release. This upgrade may impact your Angular customizations in Primo and Primo VE and may require you to adjust the customizations accordingly prior to the upgrade to ensure a smooth migration to Angular 1.8.

In advance of the November 2022 release, please carefully review the following document to ensure that your Angular customizations are ready for the update in November:

[Preparing for the Upgrade to Angular 1.8 in Primo/Primo VE] https://knowledge.exlibrisgroup.com/Primo/Product_Materials/Announcements/Preparing_for_the_Upgrade_to_Angular_1.8_in_Primo%2F%2FPrimo_VE

**Comment by MargaretA-UO** [comment]
Note:  the Alliance Primo Customization Standing Group is planning to send out more information in the Fall about how this may impact Alliance members.

**Comment by jechols** [comment]
Closing this for now - things seem good, and based on all available info we should be set for November.
