### ISSUE TITLE
VE: Links in records not obvious

### ISSUE THREAD

**Issue by MargaretA-UO** [uoregon-libraries/uolib-primo-nui#55]
In both Primo and VE (so no rush to change before VE go-live) the links within an item record are not very apparent.  I'd like us to make them more visible.  There is a faint arrow to the side of links, currently, and the link is a dark green that isn't very different from the black of other text.
![image](https://user-images.githubusercontent.com/76136640/172450691-9b33cc8b-a79a-40aa-a231-4ae35db7fd79.png)

**Comment by jechols** [comment]
What are your thoughts on the best fix? The standard underline looks like this:

![image](https://user-images.githubusercontent.com/2157974/176508079-e1468fe4-58ce-471b-8bc0-aefc46391f6c.png)

We could also go with bold and no underline:

![image](https://user-images.githubusercontent.com/2157974/176508388-6e54fae4-28b5-437c-a3b4-34ce4847a9cf.png)

Which would you prefer? Or do you have a different idea in mind?

**Comment by MargaretA-UO** [comment]
I think underlines?

**Comment by jechols** [comment]
This is live and ready for QA, @MargaretA-UO

**Comment by jechols** [comment]
FYI closing this - let me know if you have any concerns. I'm keeping it in the "ready for QA" lane on the project board (https://github.com/uoregon-libraries/uolib-primo-nui/projects/3)
