### ISSUE TITLE
VE - Advanced Search fix

### ISSUE THREAD

**Issue by MargaretA-UO** [uoregon-libraries/uolib-primo-nui#57]
Currently if user backspaces to replace a search term after performing an Advanced Search, the search disappears.  This fix is to improve usability.
[Add Buffer to Advanced Search Terms](https://github.com/alliance-pcsg/ve-customizations/blob/main/buffer-advanced-search.js)
This customization adds a buffer to the beginning of the search terms displayed under the collapsed Advanced Search form, to prevent the field from being destroyed when a patron uses the backspace. See the [video demonstration](https://drive.google.com/file/d/1vOjbQEVVf4seOzoFh90OQBQqdpdXaC0C/view?usp=sharing).

**Comment by jechols** [comment]
This is live and ready for QA, @MargaretA-UO

**Comment by jechols** [comment]
Hmm, I did a fairly simple copy/paste job for this one, other than very minor changes to fit it into our existing customization stack. Fixing this may require a fair amount of dedicated time to unravel what the alliance code is doing wrong -- or how it might be getting broken by some other customization of ours.

In the meantime is it better to keep what we have, or go back to the normal setup?

**Comment by jechols** [comment]
Removed our code, though the ExL issue is still present I think... closing this in any case.
