### ISSUE TITLE
VE: at Live, change Primo and VE banners

### ISSUE THREAD

**Issue by MargaretA-UO** [uoregon-libraries/uolib-primo-nui#59]
Primo and VE banners should now (6/28/22) read 
"LibrarySearch was upgraded on June 28th, 2022. Please update your bookmarks for LibrarySearch to https://alliance-uoregon.primo.exlibrisgroup.com/discovery/search?vid=01ALLIANCE_UO:UO and update any saved permalinks. More information about changes. (link to libguide pages https://researchguides.uoregon.edu/librarysearch-upgrade)"

**Comment by MargaretA-UO** [comment]
Sorry - I realized old Primo needs more info about not using it anymore.  Please update to 
"LibrarySearch has moved to a new location. In order to get complete results and to request items, please go to  https://alliance-uoregon.primo.exlibrisgroup.com/discovery/search?vid=01ALLIANCE_UO:UO. More information about changes. (link to libguide pages https://researchguides.uoregon.edu/librarysearch-upgrade)"

**Comment by jechols** [comment]
This is done for most pages. If you figure out a way to fix the "full record" pages, please open a new issue and assign it to me so I notice it :)

**Comment by MargaretA-UO** [comment]
It's been decided that this box and information in the new Primo VE LibrarySearch may now be removed, please.  It would be lovely to have it done before the 9th, but I realize that is short notice.
"LibrarySearch was upgraded on June 28th, 2022. Please update your bookmarks for LibrarySearch to https://alliance-uoregon.primo.exlibrisgroup.com/discovery/search?vid=01ALLIANCE_UO:UO and update any saved permalinks. [More information about changes.](https://researchguides.uoregon.edu/librarysearch-upgrade)"
Thanks!

**Comment by jechols** [comment]
I'll file a new ticket - please only reopen a ticket when the original problem still exists :)
