### ISSUE TITLE
VE:  "Library" facet blocked by customizations

### ISSUE THREAD

**Issue by MargaretA-UO** [uoregon-libraries/uolib-primo-nui#61]
In Primo we see a Library facet on the left side.  In VE, somehow the customizations are hiding this particular facet.  Kristin would really like to get it back.

The Library facet appears when I remove customizations from Primo VE by appending '&noCustomization=true' to the URL. For example, the Library facet appears here:
[https://alliance-uoregon.primo.exlibrisgroup.com/discovery/search?query=any,contains,test&tab=Rollup&search_scope=Everything&vid=01ALLIANCE_UO:UO&lang=en&offset=0&noCustomization=true](https://urldefense.com/v3/__https:/alliance-uoregon.primo.exlibrisgroup.com/discovery/search?query=any,contains,test&tab=Rollup&search_scope=Everything&vid=01ALLIANCE_UO:UO&lang=en&offset=0&noCustomization=true__;!!C5qS4YX3!ASAx7JKcMq3NTk0DhbVEXk-QtMSS85EPghqUiycvNsrjqw_NCxatn_sd87eX1525AVp_n0XPSyBlFa0oGxIMa7fGO2q_HRVf$)

I could have sworn that this was working properly until we went live with VE, so maybe a recent change?

**Comment by jechols** [comment]
This is likely to take some debugging... I'll see if I can find anything quickly, but I may need to slot some time.

**Comment by jechols** [comment]
...this looks like a really stupid bug, probably my fault when trying to combine two prior customizations (external search facet + facet collapse). Should have a fix soon.

**Comment by jechols** [comment]
Okay, I think this is fixed - ready for QA, @MargaretA-UO

**Comment by MargaretA-UO** [comment]
Huzzah!  Looks right.
Thank you for your help!

**Comment by MargaretA-UO** [comment]
Oh, good!  Thank you!
