### ISSUE TITLE
Need to limit list of 856 field links that appear in Primo VE

### ISSUE THREAD

**Issue by MargaretA-UO** [uoregon-libraries/uolib-primo-nui#64]
In VE, you can either show all links or no links.  We do have some we wish to include, so we need to use the Alliance customization Hide Unwanted 856 Links https://www.orbiscascade.org/programs/systems/pcsg/primo-ve-toolkit/hide-856-links/ 

List of what we do want to allow:

Connect to the online finding aid for this collection
Online access to digitized portions of this collection
Notice of Interest in Unprocessed Collections
Online access to digitized portions of this item
Table of contents
Display Source Record

Example record with lots of extra links: https://alliance-uoregon.primo.exlibrisgroup.com/discovery/fulldisplay?vid=01ALLIANCE_UO:UO&docid=alma99140449201852&context=L 

Example record with 3 links we want to keep: https://alliance-uoregon.primo.exlibrisgroup.com/permalink/01ALLIANCE_UO/1ej399r/alma99900500885401852

**Comment by jechols** [comment]
Just noticed this was assigned to me. If this is a priority, I need you to let me know - at the moment the earliest I think I can get to this is the 20th or so.

**Comment by MargaretA-UO** [comment]
It’s ugly, but I think you don’t need to prioritize it before then.
Thanks!

**Comment by MargaretA-UO** [comment]
Before term starts is a good goal.

**Comment by jechols** [comment]
@MargaretA-UO: FYI the text you gave me isn't complete. It must be **exactly** what's in the link. This means upper- and lower-case must match, punctuation must match, etc.

"Display Source Record" was fine as-is, and I can verify that it gets through during local development. In two other cases, a period was missing (where you wrote "Connect to the online finding aid for this collection" and "Online access to digitized portions of this collection", it needed to be "Connect to the online finding aid for this collection." and "Online access to digitized portions of this collection.")

But I'm not sure how to verify that the other items in the list are correct since they aren't in either of the two examples you provided ("Notice of Interest in Unprocessed Collections", "Online access to digitized portions of this item", and "Table of contents"). Please give me other records which I can use to verify these links (or correct them if necessary).

**Comment by MargaretA-UO** [comment]
Table of Contents
https://alliance-uoregon.primo.exlibrisgroup.com/discovery/fulldisplay?context=L&vid=01ALLIANCE_UO:UO&search_scope=Everything&tab=Rollup&docid=alma99193446301852

Notice of Interest in unprocessed collections
Online access to digitized portions of this item
![image](https://user-images.githubusercontent.com/76136640/191386794-2bff2a07-0a55-40c7-ac0f-3c8d1ba73b28.png)
An example that Austin sent some time ago, without linking to the items.  I'm asking him for example records.

**Comment by MargaretA-UO** [comment]
A record with both links:
https://alliance-uoregon.primo.exlibrisgroup.com/permalink/01ALLIANCE_UO/1ej399r/alma99107164901852

A record that only has the “Connect to the online finding aid…” link:
https://alliance-uoregon.primo.exlibrisgroup.com/permalink/01ALLIANCE_UO/1ej399r/alma99190951201852

**Comment by MargaretA-UO** [comment]
If you click on the Display Source record for these bibs, and look at the 856 field, you can see both the URL and the label.  The label is in the $z subfield.

**Comment by MargaretA-UO** [comment]
Austin says they are starting to add the Notice of interest to the 856, new practice, so we do need it in the list: 
  
https://alliance-uoregon.primo.exlibrisgroup.com/permalink/01ALLIANCE_UO/1ej399r/alma99900875597501852

**Comment by jechols** [comment]
> Table of Contents https://alliance-uoregon.primo.exlibrisgroup.com/discovery/fulldisplay?context=L&vid=01ALLIANCE_UO:UO&search_scope=Everything&tab=Rollup&docid=alma99193446301852
> 
> Notice of Interest in unprocessed collections Online access to digitized portions of this item ![image](https://user-images.githubusercontent.com/76136640/191386794-2bff2a07-0a55-40c7-ac0f-3c8d1ba73b28.png) An example that Austin sent some time ago, without linking to the items. I'm asking him for example records.

Well that's not good - it looks like in your screenshot those didn't have the period at the end. I don't know what causes those to change, but the alliance field-hide hack requires exact labels, and if those change, the links will get hidden again....

I'll get everything I can figured out, but I have no idea how we'll keep this up to date if labels change without warning. Any thoughts?

**Comment by MargaretA-UO** [comment]
Hm.  People who care about the various labels will let us know if they stop appearing.  I'll remind them that if they add labels they need to stay consistent in how they enter them.

**Comment by MargaretA-UO** [comment]
We should be able to do a search & replace to make those consistent.  I'll ask Austin to do that, since those are his.

**Comment by jechols** [comment]
That'd be perfect, thanks! Of course, if he changes from one I've added to the list to a different one, we'll have a whole new deploy to deal with.... Bleah.

**Comment by MargaretA-UO** [comment]
Can you add both labels, one with and one without the period for now?

**Comment by jechols** [comment]
Yup, I was just about to suggest the same thing. Kind of hacky, but I do think it's our best move for now.

**Comment by jechols** [comment]
I believe this is fixed as well as it can be for now. Let me know if you see anything missing or need changes.
