### ISSUE TITLE
Top Nav breakpoints in smaller screen sizes not working

### ISSUE THREAD

**Issue by MargaretA-UO** [uoregon-libraries/uolib-primo-nui#66]
Top nav should show 5, then 4, then 0 links at screen size breakpoints.  There is also some overlap happening with the logo.

**Comment by jechols** [comment]
It looks like we don't control the breakpoints. We just control how many items show up at each... the only obvious fix for the overlap is to make the middle breakpoint show only *two* links instead of four. This isn't ideal, but it might be our best quick fix.

**Comment by MargaretA-UO** [comment]
I think that is ok, since the link from the logo takes the user back to the main Libraries web page, which has most of those links on it as well.

**Comment by jechols** [comment]
All right, I'll get this deployed shortly!

**Comment by jechols** [comment]
The overlap is fixed. Is that all you needed here?

**Comment by MargaretA-UO** [comment]
I believe it is, thank you!
